#!/bin/bash

rm -rf build_new
mkdir build_new
cd build_new


cmake \
      -D CMAKE_Fortran_COMPILER=${FC}\
      -D CMAKE_C_COMPILER=${CC} \
      -D CMAKE_CXX_COMPILER=${CXX} \
      -D CMAKE_BUILD_TYPE=Debug\
      -D CMAKE_INSTALL_PREFIX=${TPLS_DIR} \
      -D NETCDF_INCLUDE_DIR=${TPLS_DIR}/include/ \
      -D PIO_INCLUDE_DIR=${TPLS_DIR}/include/ \
      -D CMAKE_INSTALL_PREFIX=${TPLS_DIR}\
      ${ATSFATES_DIR}
       
