#!/bin/tcsh

setenv FC /lustre/scratch3/turquoise/dasvyat/Amanzi/tpls/install-tools/openmpi-intel2019/bin/mpif90
setenv CC /lustre/scratch3/turquoise/dasvyat/Amanzi/tpls/install-tools/openmpi-intel2019/bin/mpicc
setenv CXX /lustre/scratch3/turquoise/dasvyat/Amanzi/tpls/install-tools/openmpi-intel2019/bin/mpicxx
setenv TPLS_DIR /lustre/scratch3/turquoise/dasvyat/Amanzi/tpls/TPLs-intel2019-0.97.1-static/
setenv MPIHOME /lustre/scratch3/turquoise/dasvyat/Amanzi/tpls/install-tools/openmpi-intel2019/

#! USER-DEFINED
setenv ATSFATES_DIR /turquoise/users/dasvyat/Coastal/ats-fates-new-copy
setenv AMANZI_SRC /turquoise/users/dasvyat/Amanzi/amanzi_ats_fates
setenv AMANZI_INSTALL /lustre/scratch3/turquoise/dasvyat/Amanzi/install-amanzi/

# if (! $?LD_LIBRARY_PATH) then       
#     setenv LD_LIBRARY_PATH ${TPLS_LIBS}
# else
#     setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${TPLS_LIBS}
# endif
