#!/bin/tcsh

setenv FC /usr/projects/hpcsoft/toss3/grizzly/openmpi/2.1.2-intel-19.0.4/bin/mpif90
setenv CC /usr/projects/hpcsoft/toss3/grizzly/openmpi/2.1.2-intel-19.0.4/bin/mpicc
setenv CXX /usr/projects/hpcsoft/toss3/grizzly/openmpi/2.1.2-intel-19.0.4/bin/mpicxx
setenv TPLS_DIR /turquoise/usr/projects/ascem/amanzi_ats_fates/tpls/TPLs-openmpi_2.1.2-intel2019-0.97.8-static-new/
setenv MPIHOME /usr/projects/hpcsoft/toss3/grizzly/openmpi/2.1.2-intel-19.0.4/

#! USER-DEFINED
setenv ATSFATES_DIR /lustre/scratch4/turquoise/.mdt5/dasvyat/Rutuja/fates-ats
setenv ATSFATES_INSTALL_DIR /lustre/scratch4/turquoise/.mdt5/dasvyat/Rutuja/fates-ats/install
